# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IO_Captcha_gRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15IO_Captcha_gRPC.proto\"\x17\n\x06String\x12\r\n\x05value\x18\x01 \x01(\t2.\n\nCalculator\x12 \n\nSquareRoot\x12\x07.String\x1a\x07.String\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IO_Captcha_gRPC_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STRING']._serialized_start=25
  _globals['_STRING']._serialized_end=48
  _globals['_CALCULATOR']._serialized_start=50
  _globals['_CALCULATOR']._serialized_end=96
# @@protoc_insertion_point(module_scope)
